import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ScrollToTop from "@/components/helpers/ScrollTop";
import "../css/card.scss";
import "../css/globals.scss";
import Footer from "@/components/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sarim Sovanden",
  description: "Generated by Sarim Sovanden",
  openGraph: {
    images:
      "https://varan100databackup.nyc3.digitaloceanspaces.com/eventcambodia/1716984975594.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen relative mx-auto px-6 sm:px-12 lg:max-w-[70rem] xl:max-w-[76rem] 2xl:max-w-[92rem] text-white">
          <Navbar />
          {children}
          <SpeedInsights />
          <ScrollToTop />
        </main>
        <Footer />
      </body>
    </html>
  );
}
